services:
  db:
    image: mariadb:10.5.8
    volumes:
      - ./data/db:/var/lib/mysql
      - ./devassets:/devassets
    environment:
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=user_name
      - MYSQL_PASSWORD=user_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=database_name
      - DATABASE_USER=user_name
      - DATABASE_PASSWORD=user_password
    depends_on:
      - db
    env_file:
      - .env


      