# Generated by Django 4.2.4 on 2024-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("everbitica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerclass",
            name="is_playable",
            field=models.BooleanField(default=False),
        ),
    ]
