# Generated by Django 3.2.25 on 2024-05-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npctype',
            name='ATK',
            field=models.BigIntegerField(default=0),
        ),
    ]
