# Generated by Django 3.2.25 on 2024-05-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bitmask', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('spell_list_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eq_classes',
            },
        ),
        migrations.AlterModelTable(
            name='zone',
            table='eq_zone',
        ),
    ]
