# Generated by Django 3.2.25 on 2024-04-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0002_playerclass_is_playable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('txtfile', models.TextField()),
            ],
            options={
                'db_table': 'eq_books',
            },
        ),
    ]
