# Generated by Django 3.2.25 on 2024-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0002_auto_20240501_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='bitmask',
            field=models.IntegerField(null=True),
        ),
    ]
