# Generated by Django 3.2.25 on 2024-05-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('base', models.SmallIntegerField(default=0)),
                ('see_illusion', models.BooleanField(default=True)),
                ('min_cap', models.SmallIntegerField(default=0)),
                ('max_cap', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'eq_faction_list',
            },
        ),
    ]
