# Generated by Django 3.2.25 on 2024-05-01 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0004_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootdrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('min_expansion', models.SmallIntegerField(default=-1)),
                ('max_expansion', models.SmallIntegerField(default=-1)),
                ('content_flags', models.CharField(max_length=100, null=True)),
                ('content_flags_disabled', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'eq_lootdrop',
            },
        ),
        migrations.CreateModel(
            name='Loottable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('mincash', models.IntegerField(default=0)),
                ('maxcash', models.IntegerField(default=0)),
                ('avgcoin', models.IntegerField(default=0)),
                ('done', models.SmallIntegerField(default=0)),
                ('min_expansion', models.SmallIntegerField(default=-1)),
                ('max_expansion', models.SmallIntegerField(default=-1)),
                ('content_flags', models.CharField(max_length=100, null=True)),
                ('content_flags_disabled', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'eq_loottable',
            },
        ),
        migrations.CreateModel(
            name='LoottableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.SmallIntegerField(default=1)),
                ('probability', models.SmallIntegerField(default=100)),
                ('droplimit', models.SmallIntegerField(default=0)),
                ('mindrop', models.SmallIntegerField(default=0)),
                ('multiplier_min', models.SmallIntegerField(default=0)),
                ('lootdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everbitica.lootdrop')),
                ('loottable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everbitica.loottable')),
            ],
            options={
                'db_table': 'eq_loottable_entries',
                'unique_together': {('loottable', 'lootdrop')},
            },
        ),
        migrations.CreateModel(
            name='LootdropEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_charges', models.SmallIntegerField(default=1)),
                ('equip_item', models.SmallIntegerField(default=0)),
                ('chance', models.FloatField(default=1)),
                ('minlevel', models.SmallIntegerField(default=0)),
                ('maxlevel', models.SmallIntegerField(default=255)),
                ('multiplier', models.SmallIntegerField(default=1)),
                ('disabled_chance', models.FloatField(default=0)),
                ('lootdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='everbitica.lootdrop')),
            ],
            options={
                'db_table': 'eq_lootdrop_entries',
                'unique_together': {('lootdrop', 'item_id')},
            },
        ),
    ]
