# Generated by Django 3.2.25 on 2024-05-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0006_auto_20240501_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('name', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=0)),
                ('no_coin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'eq_races',
            },
        ),
    ]
