# Generated by Django 3.2.25 on 2024-05-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0008_npctypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npctypes',
            name='flymode',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
