# Generated by Django 3.2.25 on 2024-05-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everbitica', '0010_auto_20240501_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npctype',
            name='_INT',
            field=models.PositiveIntegerField(db_column='_INT', default=80),
        ),
    ]
